language: rust
rust: stable

cache: cargo

before_deploy:
  - git config --local user.name "Pig Fang"
  - git config --local user.email "g-plane@hotmail.com"
  - cargo build --release
  - mkdir dist
  - cp ./target/release/yarn-autocompletions dist/
  - cp ./yarn-autocompletions.plugin.zsh dist/
  - cp ./install.sh dist/
  - cp ./README.md dist/
  - cp ./LICENSE dist/
  - cd dist
  - zip ../yarn-autocompletions_${TRAVIS_TAG}_${PLATFORM}.zip ./*
  - tar -zcvf ../yarn-autocompletions_${TRAVIS_TAG}_${PLATFORM}.tar.gz *
  - cd ..

deploy:
  provider: releases
  api_key:
    secure: y59XuDvmV4Rq/i3lVR83pHRamAmvGkp4RmLljCKE0CAPYxDkG0lA7kZTaT3Hh9vHVMTW2OyXgF6WIacTtnQAa2uj9Sv0tlQXdZAVDgT/xazzITvNW++bu9kudAlh5MA9q8ZMkCezylNiD21eH3+Yd6YlmNiMmD7rhHxDhNVSi/tl40QN10ilSYJVw7F+iCNdhT1Xd09NlZp4y1z1EKigFFArU83V2Y9LCaw+SOQMSi4pHrAXlgb5ITGnjN+X5awWO444kzV6sUBjAYvjg5YaTHoqmOcEqZi5s9tphgtD43lH8aO5TytKJQlQ7vfaG5p4iRC6DFQER4aWeVBLR4zQ+GN+McCRW+sKUxQ4lxzG++2qOfF7Kj+mvGfOCseQ4i+rDxbN/5k8XRjLMNpsUslMB9MOdqYNaQQNSBStG09LKxQjyIXklSiIt1xDY+fSwfQLkHCfvF2nLIZ4yEBQl8ADTqDQ1dV5kc6eOZ/3yJ00C/Y3a44Qm8yHJO3B+D6hq2Y3itLcFE5rSzfiwQwXf6diiCKPtPjd3GHtsHfOyyrWKQbI4G7peNomEmKDGtajFkGGjBTZBba/7fNXxZ2VkV2kJquecbOFfEsFkwUtqtHHggMZEbcknX61M1rzKyzbgyjBw9lr/K70pXz7A46n6PTRusdZT6B485h3AyYnli36duI=
  file:
    - yarn-autocompletions_${TRAVIS_TAG}_${PLATFORM}.zip
    - yarn-autocompletions_${TRAVIS_TAG}_${PLATFORM}.tar.gz
  skip_cleanup: true
  on:
    repo: g-plane/zsh-yarn-autocompletions
    branch: master
    tags: true

matrix:
  include:
    - os: osx
      env: PLATFORM=macos
    - os: linux
      env: PLATFORM=linux
