name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      PLATFORM: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Pack
        run: |
          mkdir dist
          cp ./target/release/yarn-autocompletions dist/
          cp ./yarn-autocompletions.plugin.zsh dist/
          cp ./install.sh dist/
          cp ./README.md dist/
          cp ./LICENSE dist/
          cd dist
          zip ../yarn-autocompletions_${{ matrix.os }}.zip ./*
          tar -zcvf ../yarn-autocompletions_${{ matrix.os }}.tar.gz *
          ls -l
          cd ..
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            yarn-autocompletions_${{ matrix.os }}.zip
            yarn-autocompletions_${{ matrix.os }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
